CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    service_interest TEXT NOT NULL,
    origin VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    responsible TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    last_contact_at TIMESTAMPTZ,
    next_action_at TIMESTAMPTZ,
    observation TEXT,

    CONSTRAINT chk_leads_origin CHECK (origin IN (
        'INSTAGRAM',
        'LANDING_PAGE',
        'GOOGLE',
        'REFERRAL',
        'WHATSAPP',
        'RETURNING_CLIENT',
        'OTHER'
    )),
    CONSTRAINT chk_leads_status CHECK (status IN (
        'NEW',
        'CONTACTED',
        'WAITING_CLIENT',
        'WAITING_SCHEDULE',
        'SCHEDULED',
        'RESCHEDULE_REQUIRED',
        'COMPLETED',
        'LOST'
    )),
    CONSTRAINT chk_leads_next_action_required CHECK (
        status NOT IN ('WAITING_CLIENT', 'WAITING_SCHEDULE', 'RESCHEDULE_REQUIRED')
        OR next_action_at IS NOT NULL
    )
);
